version: '3.8'
services:
  db:
    hostname: db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - '5432'
    env_file:
      - '.env'
volumes:
  db:
    driver: local
